name: AfterLifePlugin
version: ${project.version}
main: me.yodeling_goat.afterlifeplugin.AfterLifePlugin
api-version: 1.13
description: send your players to heaven or hell!

commands:
  exitafterlife:
    description: Exit the afterlife state
    usage: /<command>
    permission: afterlife.exit
  checkafterlife:
    description: Check if you are in the afterlife
    usage: /<command>
    permission: afterlife.check
  forceexitafterlife:
    description: Force remove a player from the afterlife (Admin only)
    usage: /<command> <player>
    permission: afterlife.admin
  morphdebug:
    description: Debug morphing system
    usage: /<command>
    permission: afterlife.admin
  testmorph:
    description: Test morphing into a nearby mob
    usage: /<command>
    permission: afterlife.admin
  enterafterlife:
    description: Enter the afterlife state for testing (Admin only)
    usage: /<command>
    permission: afterlife.admin
